import { expect, test } from '@playwright/test'

const TEST = {
  cancel: 'leaving during a pending diagram load never mounts the stale runtime',
  direct: 'Amiit renders its source graph with working controls at every viewport',
  switching: 'diagram assets load independently and runtime state is isolated when switching projects',
}
const PATH = {
  alektions: '/see/alektions-election-events-map',
  amiit: '/see/amiit-platform-architecture',
  focus: '#focus=api',
  home: '/',
  see: '/see',
}
const UI = {
  amiit: 'Amiit.AI: Platform Architecture',
  back: 'Selected work',
  dark: 'Dark',
  light: 'Light',
  site: 'Arye Zamir',
}
const SELECTOR = {
  api: '.diagram-container > svg #node-api',
  canvas: '.diagram-container',
  controls: '.diagram-nav',
  edges: '.diagram-container > svg path[data-edge-id]',
  finder: '#node-finder',
  finderInput: '#node-finder-input',
  guided: '#guided-views',
  header: 'h1',
  nodes: '.diagram-container > svg [data-node-id]',
  root: '.architecture-diagram',
  svg: '.diagram-container > svg',
  zampa: '.diagram-container > svg #node-zampa',
}
const ATTRIBUTE = { diagram: 'data-diagram', enabled: 'true', pressed: 'aria-pressed', theme: 'data-theme' }
const ID = { alektions: 'alektions-election-events-map', amiit: 'amiit-platform-architecture' }
const VALUE = { centerDivisor: 2, nodes: 18, none: 0, one: 1, scroll: 100, tolerance: 2 }
const EVENT = { error: 'pageerror', request: 'request' }
const KEY = { escape: 'Escape', find: '/', theme: 't' }
const SEARCH = { result: /^Focus Amiit \(Agent\),/, term: 'Amiit (Agent)' }
const THEME = { dark: 'dark', light: 'light' }
const ASSET = { alektions: /AlektionsDiagramView-.*\.js/, amiit: /AmiitDiagramView-.*\.js/ }
const SHOT = { animations: 'disabled', dark: 'amiit-dark.png', light: 'amiit-light.png' }
const SCROLL = { behavior: 'instant', routing: 'wait' }
const RELATIONSHIPS = [
  'clients>app',
  'transports>api',
  'app>api',
  'api>idp',
  'api>channels',
  'channels>zampa',
  'api>zampa',
  'idp>zampa',
  'idp>idpdata',
  'zampa>anthropic',
  'zampa>tools',
  'zampa>zammcp',
  'zampa>zmem',
  'tools>google',
  'zammcp>vikunja',
  'zammcp>forgejo',
  'zammcp>minio',
  'zammcp>bitwarden',
  'zampa>redis',
]
const EDGE = { from: 'data-edge-from', separator: '>', to: 'data-edge-to' }
const FORBIDDEN = /[\u2013\u2014]|--|generated by Archify|zammcp MCP|zamemory|agent gateway/

test(TEST.direct, async ({ page }, testInfo) => {
  const errors = []
  page.on(EVENT.error, (error) => errors.push(error.message))
  await page.goto(PATH.amiit + PATH.focus)
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.amiit)
  await expect(page.locator(SELECTOR.header)).toHaveText(UI.amiit)
  await expect(page.locator(SELECTOR.nodes)).toHaveCount(VALUE.nodes)
  await expect(page.locator(SELECTOR.api)).toHaveAttribute(ATTRIBUTE.pressed, ATTRIBUTE.enabled)
  await expect(page.locator(SELECTOR.guided)).toBeHidden()
  const relationships = await page
    .locator(SELECTOR.edges)
    .evaluateAll(
      (edges, attribute) =>
        edges
          .map((edge) => edge.getAttribute(attribute.from) + attribute.separator + edge.getAttribute(attribute.to))
          .sort(),
      EDGE,
    )
  expect(relationships).toEqual([...RELATIONSHIPS].sort())
  await expect(page.locator(SELECTOR.root)).not.toContainText(FORBIDDEN)
  await page.keyboard.press(KEY.escape)
  await page.keyboard.press(KEY.find)
  await page.locator(SELECTOR.finderInput).fill(SEARCH.term)
  await page.locator(SELECTOR.finder).getByRole('button', { name: SEARCH.result }).click()
  await expect(page.locator(SELECTOR.zampa)).toHaveAttribute(ATTRIBUTE.pressed, ATTRIBUTE.enabled)
  await page.keyboard.press(KEY.escape)
  await page.getByRole('button', { exact: true, name: UI.light }).click()
  const offsets = await page.locator(SELECTOR.canvas).evaluate(
    (canvas, { scroll, selector, value }) => {
      const nav = canvas.querySelector(selector.controls)
      return [value.none, value.scroll, canvas.scrollWidth, value.none].map((left) => {
        canvas.scrollTo({ behavior: scroll.behavior, left })
        const stage = canvas.getBoundingClientRect()
        const toolbar = nav.getBoundingClientRect()
        return Math.abs(toolbar.x + toolbar.width / value.centerDivisor - stage.x - stage.width / value.centerDivisor)
      })
    },
    { scroll: SCROLL, selector: SELECTOR, value: VALUE },
  )
  for (const offset of offsets) expect(offset).toBeLessThan(VALUE.tolerance)
  await page.locator(SELECTOR.root).evaluate((root, scroll) => void root.ownerDocument.defaultView.scrollTo(scroll), {
    behavior: SCROLL.behavior,
    top: VALUE.none,
  })
  await page.screenshot({ animations: SHOT.animations, fullPage: true, path: testInfo.outputPath(SHOT.light) })
  await page.getByRole('button', { exact: true, name: UI.dark }).click()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.theme, THEME.dark)
  await page.locator(SELECTOR.root).evaluate((root, scroll) => void root.ownerDocument.defaultView.scrollTo(scroll), {
    behavior: SCROLL.behavior,
    top: VALUE.none,
  })
  await page.screenshot({ animations: SHOT.animations, fullPage: true, path: testInfo.outputPath(SHOT.dark) })
  expect(errors).toEqual([])
})

test(TEST.switching, async ({ page }) => {
  const assets = []
  const errors = []
  page.on(EVENT.error, (error) => errors.push(error.message))
  page.on(EVENT.request, (request) => assets.push(request.url()))
  await page.goto(PATH.see)
  expect(assets.some((url) => ASSET.amiit.test(url) || ASSET.alektions.test(url))).toBe(false)
  await page.locator(`.portfolio-diagram h2 a[href="${PATH.alektions}"]`).click()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.alektions)
  expect(assets.some((url) => ASSET.alektions.test(url))).toBe(true)
  expect(assets.some((url) => ASSET.amiit.test(url))).toBe(false)
  await page.keyboard.press(KEY.find)
  await expect(page.locator(SELECTOR.finder)).toBeVisible()
  await page.getByRole('link', { name: UI.back }).click()
  await page.locator(`.portfolio-diagram h2 a[href="${PATH.amiit}"]`).click()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.amiit)
  await expect(page.locator(SELECTOR.root)).toHaveCount(VALUE.one)
  await expect(page.locator(SELECTOR.finder)).toBeHidden()
  await expect(page.locator(SELECTOR.nodes)).toHaveCount(VALUE.nodes)
  expect(assets.some((url) => ASSET.amiit.test(url))).toBe(true)
  await page.keyboard.press(KEY.theme)
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.theme, THEME.dark)
  await page.goBack()
  await expect(page).toHaveURL(PATH.see)
  await expect(page.locator(SELECTOR.root)).toHaveCount(VALUE.none)
  await page.goBack()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.alektions)
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.theme, THEME.dark)
  expect(errors).toEqual([])
})

test(TEST.cancel, async ({ page }) => {
  const requested = Promise.withResolvers()
  const release = Promise.withResolvers()
  const finished = Promise.withResolvers()
  await page.route(ASSET.amiit, async (route) => {
    requested.resolve()
    await release.promise
    await route.continue()
    finished.resolve()
  })
  await page.goto(PATH.see)
  await page.locator(`.portfolio-diagram h2 a[href="${PATH.amiit}"]`).click()
  await requested.promise
  await page.getByRole('link', { exact: true, name: UI.site }).click()
  await expect(page).toHaveURL(PATH.home)
  release.resolve()
  await finished.promise
  await page.unrouteAll({ behavior: SCROLL.routing })
  await expect(page.locator(SELECTOR.root)).toHaveCount(VALUE.none)
  await page.locator(`.site-header a[href="${PATH.see}"]`).click()
  await page.locator(`.portfolio-diagram h2 a[href="${PATH.amiit}"]`).click()
  await expect(page.locator(SELECTOR.nodes)).toHaveCount(VALUE.nodes)
})
