import { expect, test } from '@playwright/test'

const TEST = {
  direct: 'Commodity renders its source graph with working controls at every viewport',
  switching: 'diagram assets load independently and runtime state is isolated when switching projects',
}
const PATH = {
  alektions: '/see/alektions-election-events-map',
  commodity: '/see/commodity-trading-platform',
  focus: '#focus=portal',
  see: '/see',
}
const UI = {
  back: 'Selected work',
  commodity: 'Multi-Channel Commodity Trading Platform',
  dark: 'Dark',
  database: 'Database',
  light: 'Light',
  redis: 'Redis',
}
const SELECTOR = {
  assistant: '.diagram-container > svg #node-agent',
  canvas: '.diagram-container',
  controls: '.diagram-nav',
  edges: '.diagram-container > svg path[data-edge-id]',
  finder: '#node-finder',
  finderInput: '#node-finder-input',
  guided: '#guided-views',
  header: 'h1',
  nodes: '.diagram-container > svg [data-node-id]',
  portal: '.diagram-container > svg #node-portal',
  redis: '.diagram-container > svg #node-mcpdb',
  root: '.architecture-diagram',
  vikunjaDatabase: '.diagram-container > svg #node-vikunjadb',
}
const ATTRIBUTE = {
  diagram: 'data-diagram',
  enabled: 'true',
  label: 'data-node-label',
  pressed: 'aria-pressed',
  theme: 'data-theme',
}
const ID = { alektions: 'alektions-election-events-map', commodity: 'commodity-trading-platform' }
const VALUE = { centerDivisor: 2, nodes: 15, none: 0, one: 1, scroll: 100, tolerance: 2 }
const EVENT = { error: 'pageerror', request: 'request' }
const KEY = { escape: 'Escape', find: '/', theme: 't' }
const SEARCH = { result: /^Focus Amiit\.ai,/, term: 'Amiit.ai' }
const THEME = { dark: 'dark', light: 'light' }
const ASSET = { alektions: /AlektionsDiagramView-.*\.js/, commodity: /CommodityDiagramView-.*\.js/ }
const SHOT = { animations: 'disabled', dark: 'commodity-dark.png', light: 'commodity-light.png' }
const SCROLL = { behavior: 'instant' }
const CHAPTERS = [
  { label: /^(?:Open|Current) chapter 1 of 3: Gateway and authentication/, url: /#view=channels/ },
  { label: /^(?:Open|Current) chapter 2 of 3: AI personal assistant/, url: /#view=identity/ },
  { label: /^(?:Open|Current) chapter 3 of 3: Business core/, url: /#view=domain/ },
]
const RELATIONSHIPS = [
  'web>gateway',
  'mobile>gateway',
  'gateway>idp',
  'gateway>agent',
  'gateway>portal',
  'agent>mcp',
  'mcp>docs',
  'mcp>erp',
  'mcp>vikunja',
  'portal>docs',
  'portal>erp',
  'portal>vikunja',
  'idp>idpdb',
  'mcp>mcpdb',
  'portal>portaldb',
  'erp>erpdb',
  'vikunja>vikunjadb',
]
const EDGE = { from: 'data-edge-from', separator: '>', to: 'data-edge-to' }
const ROLE = { button: 'button' }
const CURRENT = { attribute: 'aria-current', value: 'step' }
const FORBIDDEN = /[\u2013\u2014]|--|generated by Archify/

test(TEST.direct, async ({ page }, testInfo) => {
  const errors = []
  page.on(EVENT.error, (error) => errors.push(error.message))
  await page.goto(PATH.commodity + PATH.focus)
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.commodity)
  await expect(page.locator(SELECTOR.header)).toHaveText(UI.commodity)
  await expect(page.locator(SELECTOR.nodes)).toHaveCount(VALUE.nodes)
  await expect(page.locator(SELECTOR.portal)).toHaveAttribute(ATTRIBUTE.pressed, ATTRIBUTE.enabled)
  const relationships = await page
    .locator(SELECTOR.edges)
    .evaluateAll(
      (edges, attribute) =>
        edges
          .map((edge) => edge.getAttribute(attribute.from) + attribute.separator + edge.getAttribute(attribute.to))
          .sort(),
      EDGE,
    )
  expect(relationships).toEqual([...RELATIONSHIPS].sort())
  await expect(page.locator(SELECTOR.redis)).toHaveAttribute(ATTRIBUTE.label, UI.redis)
  await expect(page.locator(SELECTOR.vikunjaDatabase)).toHaveAttribute(ATTRIBUTE.label, UI.database)
  await expect(page.locator(SELECTOR.guided)).toBeVisible()
  await expect(page.locator(SELECTOR.root)).not.toContainText(FORBIDDEN)
  await page.keyboard.press(KEY.escape)
  await page.keyboard.press(KEY.find)
  await page.locator(SELECTOR.finderInput).fill(SEARCH.term)
  await page.locator(SELECTOR.finder).getByRole(ROLE.button, { name: SEARCH.result }).click()
  await expect(page.locator(SELECTOR.assistant)).toHaveAttribute(ATTRIBUTE.pressed, ATTRIBUTE.enabled)
  await page.keyboard.press(KEY.escape)
  for (const chapter of CHAPTERS) {
    const button = page.getByRole(ROLE.button, { name: chapter.label })
    await button.click()
    await expect(page).toHaveURL(chapter.url)
    await expect(button).toHaveAttribute(CURRENT.attribute, CURRENT.value)
  }
  await page.keyboard.press(KEY.escape)
  await page.getByRole(ROLE.button, { exact: true, name: UI.light }).click()
  const offsets = await page.locator(SELECTOR.canvas).evaluate(
    (canvas, { scroll, selector, value }) => {
      const nav = canvas.querySelector(selector.controls)
      return [value.none, value.scroll, canvas.scrollWidth, value.none].map((left) => {
        canvas.scrollTo({ behavior: scroll.behavior, left })
        const stage = canvas.getBoundingClientRect()
        const toolbar = nav.getBoundingClientRect()
        return Math.abs(toolbar.x + toolbar.width / value.centerDivisor - stage.x - stage.width / value.centerDivisor)
      })
    },
    { scroll: SCROLL, selector: SELECTOR, value: VALUE },
  )
  for (const offset of offsets) expect(offset).toBeLessThan(VALUE.tolerance)
  await page.locator(SELECTOR.root).evaluate((root, scroll) => void root.ownerDocument.defaultView.scrollTo(scroll), {
    behavior: SCROLL.behavior,
    top: VALUE.none,
  })
  await page.screenshot({ animations: SHOT.animations, fullPage: true, path: testInfo.outputPath(SHOT.light) })
  await page.getByRole(ROLE.button, { exact: true, name: UI.dark }).click()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.theme, THEME.dark)
  await page.locator(SELECTOR.root).evaluate((root, scroll) => void root.ownerDocument.defaultView.scrollTo(scroll), {
    behavior: SCROLL.behavior,
    top: VALUE.none,
  })
  await page.screenshot({ animations: SHOT.animations, fullPage: true, path: testInfo.outputPath(SHOT.dark) })
  expect(errors).toEqual([])
})

test(TEST.switching, async ({ page }) => {
  const assets = []
  const errors = []
  page.on(EVENT.error, (error) => errors.push(error.message))
  page.on(EVENT.request, (request) => assets.push(request.url()))
  await page.goto(PATH.see)
  expect(assets.some((url) => ASSET.commodity.test(url) || ASSET.alektions.test(url))).toBe(false)
  await page.locator(`.portfolio-diagram h2 a[href="${PATH.alektions}"]`).click()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.alektions)
  expect(assets.some((url) => ASSET.alektions.test(url))).toBe(true)
  expect(assets.some((url) => ASSET.commodity.test(url))).toBe(false)
  await page.keyboard.press(KEY.find)
  await expect(page.locator(SELECTOR.finder)).toBeVisible()
  await page.getByRole('link', { name: UI.back }).click()
  await page.locator(`.portfolio-diagram h2 a[href="${PATH.commodity}"]`).click()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.commodity)
  await expect(page.locator(SELECTOR.root)).toHaveCount(VALUE.one)
  await expect(page.locator(SELECTOR.finder)).toBeHidden()
  await expect(page.locator(SELECTOR.nodes)).toHaveCount(VALUE.nodes)
  expect(assets.some((url) => ASSET.commodity.test(url))).toBe(true)
  await page.keyboard.press(KEY.theme)
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.theme, THEME.dark)
  await page.goBack()
  await expect(page).toHaveURL(PATH.see)
  await expect(page.locator(SELECTOR.root)).toHaveCount(VALUE.none)
  await page.goBack()
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.diagram, ID.alektions)
  await expect(page.locator(SELECTOR.root)).toHaveAttribute(ATTRIBUTE.theme, THEME.dark)
  expect(errors).toEqual([])
})
